### ISSUE TITLE
Relay Modern TypeError: Class extends value undefined is not a function or null

### ISSUE THREAD

**Issue by aljones15** [meuschke/relay-testing-utils#3]
just to make sure does this work with Relay Modern?

getting the error:

TypeError: Class extends value undefined is not a function or null
  1 import relayTestingUtils from 'relay-testing-utils';
  2 import { mount } from 'enzyme';
  3 import City from './index';
  4 
  5 const City_item = {
  6   _id: 1
  7 } 
  8 
  9 describe('map should', () => {
 10   const elJson = mount(
 11     relayTestingUtils.wrapRelay(<City {...City_item} />)
 12    );
 13   it('match a snapshot', () => {
 14     //expect(elJson).toMatchSnapshot();
 15   });
 16 });

**Comment by AdrienLemaire** [comment]
Same problem here with relay modern
```
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null
      
      at Object.relayMock (node_modules/relay-testing-utils/build/relay-mock.js:9:31)
      at Object.<anonymous> (src/components/__mocks__/react-relay.js:5:29)
      at Object.<anonymous> (src/components/Dashboard/Projects.js:3:19)
      at Object.<anonymous> (src/components/Dashboard/__tests__/Projects-test.js:7:17)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by aljones15** [comment]
I'm going to try to fork this project this weekend and make a mock for modern. shouldn't be to hard. the library is intended for classic I checked.

**Comment by aljones15** [comment]
looks like relay modern is easier to mock too

  2 const relay = jest.genMockFromModule('react-relay');
  3 
  4 relay.createFragmentContainer = (c) => c;
  5 
  6 module.exports = relay;

put that in __mocks__/react-relay.js

that seems to work ok then just pass the expected relay props in on data or the prop they usually bind too. no need for this package it looks like with modern.
